### ISSUE TITLE
hosting bot

### ISSUE THREAD

**Issue by thenamelessthing** [LEGENDARY-KING/PDF-Viewer-Bot#2]
Hi, I have added the bot on my server. But when I try to run the command: /read link: https://mydomain.com/index.php/s/5BYTGen5yHNrirr

Nothing happened.

![image](https://github.com/LEGENDARY-KING/PDF-Viewer-Bot/assets/10235448/58d4ba7f-32e9-45ad-b08d-732bfe641e61)

Just to be sure, once I copied your bot file on my linux server, I also installed discord.js and started the bot with the following command: node index.js 

I also provided to the bot the following permission:

![image](https://github.com/LEGENDARY-KING/PDF-Viewer-Bot/assets/10235448/4005a866-b6f3-4c8a-926a-bef1fae30268)

Any idea?

Thank a lot!

**Comment by aarush-salgania** [comment]
You need to have SLASH commands not message commands, they dont work anymore. Add the bot again with "applications.commands" scope and then try by using the slash command not message.

**Comment by thenamelessthing** [comment]
Now I've kicked the bot off the server, I've modified the rights with these. And I reinvited the bot.

![image](https://github.com/LEGENDARY-KING/PDF-Viewer-Bot/assets/10235448/fa676ef9-cadc-4960-8b0d-087c134fbd1d)

When I type the "/" the bot is not showed..

![image](https://github.com/LEGENDARY-KING/PDF-Viewer-Bot/assets/10235448/be076f6c-5d3c-4310-983d-552acd9c5a9f)

**Comment by thenamelessthing** [comment]
Once the bot is added on my server. Do I need to run a specific command to initialize the bot? Or just start using it withe the slash command?

**Comment by aarush-salgania** [comment]
you have to run the deploy-commands.js file too with your bot's information

**Comment by aarush-salgania** [comment]
Ive added an invite link for a copy of this which im hosting. Feel free to use that https://discord.com/oauth2/authorize?client_id=955091852695064606&permissions=52224&scope=bot%20applications.commands

**Comment by thenamelessthing** [comment]
> you have to run the deploy-commands.js file too with your bot's information

Okay, I think I'm almost there. Is the Guild ID mandatory? I don't think I have a guild ID, at least I don't know what it is if I do. So I tried without specifying it but it doesn't seem to work.

![image](https://github.com/LEGENDARY-KING/PDF-Viewer-Bot/assets/10235448/a1b3b518-62a5-4c7c-ae8c-2ff1dfd64621)

**Comment by aarush-salgania** [comment]
Guild ID is your server ID. If you want the commands to be global then replace the line from `applicationGuildCommands` to `applicationCommands` and just do clientId

**Comment by aarush-salgania** [comment]
update?

**Comment by thenamelessthing** [comment]
yes, with your help It's almost done!

Now I got this: 

![image](https://github.com/LEGENDARY-KING/PDF-Viewer-Bot/assets/10235448/ddb4939e-7c1a-4c63-9369-13e53456005d)


What do you mean by "outputFileMask"?

**Comment by aarush-salgania** [comment]
read the readme, you have to make changes to a node module

**Comment by aarush-salgania** [comment]
I just saw the latest version for that node module. You can install the latest one and you will just have to change the total pages one

**Comment by thenamelessthing** [comment]
It seem that in the latest version I don't have the convert.to.png.js file.

![image](https://github.com/LEGENDARY-KING/PDF-Viewer-Bot/assets/10235448/ba3df3b9-6169-4cb8-9b8d-442a433035ac)

I have the module version:
![image](https://github.com/LEGENDARY-KING/PDF-Viewer-Bot/assets/10235448/6d3d1d3e-f78a-41e4-af88-9f6340c42182)

**Comment by aarush-salgania** [comment]
check using `npm list`. Get the 0.2.2 version. `npm i pdf-to-png-converter@0.2.2`

**Comment by thenamelessthing** [comment]
I got this:

![image](https://github.com/LEGENDARY-KING/PDF-Viewer-Bot/assets/10235448/030d18f4-8ef1-4af9-aad0-f27a48eabab5)

And I don't find where I must modify the line 116. My file only have 96 lines..

![image](https://github.com/LEGENDARY-KING/PDF-Viewer-Bot/assets/10235448/723e950e-c0c8-46ea-a391-45e3813dbc51)

The content of the file convert.to.png.js

![image](https://github.com/LEGENDARY-KING/PDF-Viewer-Bot/assets/10235448/66fde6ee-2cc4-40a8-a264-9da087e08bbe)

Now I obtain this error when I try ..

![image](https://github.com/LEGENDARY-KING/PDF-Viewer-Bot/assets/10235448/d5d127d4-51b9-4e86-9011-bfb08b49fd55)

**Comment by aarush-salgania** [comment]
edit the other lines too. And for your file add the 116 line after 85

**Comment by aarush-salgania** [comment]
Or you can juse use this one
```js
"use strict";
var __createBinding =
  (this && this.__createBinding) ||
  (Object.create
    ? function (o, m, k, k2) {
        if (k2 === undefined) k2 = k;
        var desc = Object.getOwnPropertyDescriptor(m, k);
        if (
          !desc ||
          ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)
        ) {
          desc = {
            enumerable: true,
            get: function () {
              return m[k];
            },
          };
        }
        Object.defineProperty(o, k2, desc);
      }
    : function (o, m, k, k2) {
        if (k2 === undefined) k2 = k;
        o[k2] = m[k];
      });
var __setModuleDefault =
  (this && this.__setModuleDefault) ||
  (Object.create
    ? function (o, v) {
        Object.defineProperty(o, "default", { enumerable: true, value: v });
      }
    : function (o, v) {
        o["default"] = v;
      });
var __importStar =
  (this && this.__importStar) ||
  function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null)
      for (var k in mod)
        if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k))
          __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
  };
Object.defineProperty(exports, "__esModule", { value: true });
exports.pdfToPng = void 0;
const fs_1 = require("fs");
const path_1 = require("path");
const pdfjs = __importStar(require("pdfjs-dist/legacy/build/pdf"));
const node_canvas_factory_1 = require("./node.canvas.factory");
const cMapUrl = "../node_modules/pdfjs-dist/cmaps/";
const cMapPacked = true;
async function pdfToPng(pdfFilePathOrBuffer, props) {
  const isBuffer = Buffer.isBuffer(pdfFilePathOrBuffer);
  if (!isBuffer && !(0, fs_1.existsSync)(pdfFilePathOrBuffer)) {
    throw Error(`PDF file not found on: ${pdfFilePathOrBuffer}.`);
  }
  if (
    props?.outputFilesFolder &&
    !(0, fs_1.existsSync)(props.outputFilesFolder)
  ) {
    (0, fs_1.mkdirSync)(props.outputFilesFolder, { recursive: true });
  }
  /* if (!props?.outputFileMask && isBuffer) {
        throw Error('outputFileMask is required when input is a Buffer.');
    }*/
  const pdfFileBuffer = isBuffer
    ? pdfFilePathOrBuffer
    : (0, fs_1.readFileSync)(pdfFilePathOrBuffer);
  const pdfDocInitParams = {
    data: new Uint8Array(pdfFileBuffer),
    cMapUrl,
    cMapPacked,
  };
  pdfDocInitParams.disableFontFace = props?.disableFontFace ?? true;
  pdfDocInitParams.useSystemFonts = props?.useSystemFonts ?? false;
  if (props?.pdfFilePassword) {
    pdfDocInitParams.password = props?.pdfFilePassword;
  }
  const pdfDocument = await pdfjs.getDocument(pdfDocInitParams).promise;
  const pngPagesOutput = [];
  const targetedPages = props?.pages
    ? props.pages
    : Array.from({ length: pdfDocument.numPages }, (_, index) => index + 1);
  if (targetedPages.some((pageNum) => pageNum < 1)) {
    throw new Error("Invalid pages requested, page numbers must be >= 1");
  }
  for (const pageNumber of targetedPages) {
    if (pageNumber > pdfDocument.numPages) {
      // If a requested page is beyond the PDF bounds we skip it.
      // This allows the use case "generate up to the first n pages from a set of input PDFs"
      continue;
    }
    const page = await pdfDocument.getPage(pageNumber);
    const viewport = page.getViewport({ scale: props?.viewportScale ?? 1.0 });
    const canvasFactory = new node_canvas_factory_1.NodeCanvasFactory();
    const canvasAndContext = canvasFactory.create(
      viewport.width,
      viewport.height
    );
    const renderContext = {
      canvasContext: canvasAndContext.context,
      viewport,
      canvasFactory,
    };
    await page.render(renderContext).promise;

    let pageName;
    if (!isBuffer) pageName = path_1.parse(pdfFilePathOrBuffer).name;
    if (!pageName) pageName = props?.outputFileMask ?? "No_File_Name";
    const pngPageOutput = {
      name: `${pageName}_page_${pageNumber}.png`,
      content: canvasAndContext.canvas.toBuffer(),
      path: "",
      totalPages: pdfDocument.numPages,
    };
    if (props?.outputFilesFolder) {
      pngPageOutput.path = (0, path_1.resolve)(
        props.outputFilesFolder,
        pngPageOutput.name
      );
      (0, fs_1.writeFileSync)(pngPageOutput.path, pngPageOutput.content);
    }
    pngPagesOutput.push(pngPageOutput);
  }
  return pngPagesOutput;
}
exports.pdfToPng = pdfToPng;
//# sourceMappingURL=convert.to.png.js.map
```

**Comment by thenamelessthing** [comment]
You make my day, it's working!!  Thank you a lot for your help. I will use it and let you know if something doesn't work. Have a nice weekend!

**Comment by aarush-salgania** [comment]
Cheers
